# --- !Ups

CREATE TABLE locations (
	location_id serial PRIMARY KEY,
  location_name text,
  location_parent int REFERENCES locations(location_id)
);;

INSERT INTO locations (location_id, location_name, location_parent) VALUES
	(0, 'All', NULL),
	(1, 'Foreign', 0),
	(2, 'Local', 0),
	(3, 'Nationwide', 2),
	(4, 'Region VI', 28),
	(5, 'CO', 2),
	(6, 'Region III', 26),
	(7, 'Region IV-A', 26),
	(8, 'Region VII', 28),
	(9, 'Region V', 26),
	(10, 'Region VIII', 28),
	(11, 'National Capital Region', 26),
	(12, 'Region I', 26),
	(13, 'Region II', 26),
	(14, 'Region X', 24),
	(15, 'Region IX', 24),
	(16, 'Region XII', 24),
	(17, 'Region XI', 24),
	(18, 'Region XIII', 24),
	(19, 'Region IV-B', 26),
	(20, 'Cordillera Administrative Region', 26),
	(21, 'Autonomous Region in Muslim Mindanao', 24),
	(22, 'Region IV', 26),
	(23, 'Metro Manila', 26),
	(24, 'Mindanao', 3),
	(25, 'Indonesia, Jakarta', 1),
	(26, 'Luzon', 3),
	(27, 'Saudi Arabia, Riyadh', 1),
	(28, 'Visayas', 3),
	(29, 'Cagayan', 13),
	(30, 'Switzerland, Geneva', 1),
	(31, '', 0),
	(32, 'U.S.A., New York', 1),
	(33, 'China, Beijing', 1),
	(34, 'Caracas, Venezuela', 1),
	(35, 'France, Paris', 1),
	(36, 'Saudi Arabia, Jeddah', 1),
	(37, 'United Kingdom, London', 1),
	(38, 'Japan, Tokyo', 1),
	(39, 'U.S.A., Washington, D.C.', 1),
	(40, 'Phomn Penh, Cambodia', 1),
	(41, 'U.A.E., Abu Dhabi', 1),
	(42, 'Jordan, Amman', 1),
	(43, 'U.S.A., Honolulu', 1),
	(44, 'Laos, Vientianne', 1),
	(45, 'India, New Delhi', 1),
	(46, 'Italy, Rome', 1),
	(47, 'Pretoria, South Africa', 1),
	(48, 'Malaysia, Kuala Lumpur', 1),
	(49, 'Japan, Kobe', 1),
	(50, 'Vatican, Holy See', 1),
	(51, 'Israel, Tel-Aviv', 1),
	(52, 'C.I.S., Moscow', 1),
	(53, 'Argentina, Buenos Aires', 1),
	(54, 'Canada, Toronto', 1),
	(55, 'Hungary, Budapest', 1),
	(56, 'Austria, Vienna', 1),
	(57, 'Belgium, Brussels', 1),
	(58, 'Brazil, Brasilia', 1),
	(59, 'U.S.A., San Francisco', 1),
	(60, 'U.S.A., Agana', 1),
	(61, 'Qatar, Doha', 1),
	(62, 'Nigeria, Lagos', 1),
	(63, 'Pakistan, Islamabad', 1),
	(64, 'U.S.A., Chicago', 1),
	(65, 'Kuwait, Kuwait', 1),
	(66, 'Mexico, Mexico', 1),
	(67, 'Iraq, Baghdad', 1),
	(68, 'Singapore, Singapore', 1),
	(69, 'Switzerland, Berne', 1),
	(70, 'New Zealand, Wellington', 1),
	(71, 'Libya, Tripoli', 1),
	(72, 'Lebanon, Beirut', 1),
	(73, '3rd District, Pangasinan, San Carlos City', 12),
	(74, 'Chile, Santiago', 1),
	(75, 'Papua New Guinea, P. Moresby', 1),
	(76, 'Hongkong, Hongkong', 1),
	(77, 'Germany, Bonn', 1),
	(78, 'Canada, Ottawa', 1),
	(79, 'Korea South, Seoul', 1),
	(80, 'Bangladesh, Dhaka', 1),
	(81, 'Kenya, Nairobi', 1),
	(82, 'Xiamen, China', 1),
	(83, 'Brunei, Bandar Seri Begawan', 1),
	(84, 'Iran, Teheran', 1),
	(85, 'Oman, Muscat', 1),
	(86, 'Australia, Sydney', 1),
	(87, 'Thailand, Bangkok', 1),
	(88, 'Egypt, Cairo', 1),
	(89, 'Australia, Canberra', 1),
	(90, 'Turkey, Ankara', 1),
	(91, 'Republic of Czechoslovakia, Prague', 1),
	(92, 'Myanmar, Yangon', 1),
	(93, 'Vietnam, Hanoi', 1),
	(94, 'Netherlands, The Hague', 1),
	(95, 'Canada, Vancouver', 1),
	(96, 'Greece, Athens', 1),
	(97, 'Indonesia, Manado', 1),
	(98, 'Milan, Italy', 1),
	(99, 'Guangzhou, China', 1),
	(100, 'U.S.A., Los Angeles', 1),
	(101, 'Bahrain, Manama', 1),
	(102, 'Spain, Madrid', 1),
	(103, 'Sweden, Stockholm', 1),
	(104, 'Vietnam, Ho Chi Minh', 1),
	(105, 'Cuba, Havana', 1),
	(106, 'Micronesia, Pohnpei', 1),
	(107, 'Vladivostok, Russia', 1),
	(108, 'Saipan, Saipan', 1),
	(109, 'Republic of Palau, Koror', 1),
	(110, 'Germany, Hamburg', 1),
	(111, 'Romania, Bucharest', 1)
;;

ALTER TABLE locations
	ADD location_ps int NOT NULL DEFAULT 0,
  ADD location_mooe int NOT NULL DEFAULT 0,
  ADD location_co int NOT NULL DEFAULT 0,
  ADD location_stars int NOT NULL DEFAULT 0,
  ADD location_ratings int NOT NULL DEFAULT 0
;;

# --- !Downs

DROP TABLE IF EXISTS locations;;
